include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = MomoAIPrefs
MomoAIPrefs_FILES = MOMOPrefsController.mm
MomoAIPrefs_INSTALL_PATH = /Library/PreferenceBundles
MomoAIPrefs_PRIVATE_FRAMEWORKS = Preferences
MomoAIPrefs_FRAMEWORKS = UIKit Foundation
MomoAIPrefs_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
